import { NextRequest, NextResponse } from "next/server";
import { randomUUID } from "crypto";
import prisma from "@/lib/prisma";
import { isAuthError } from "@/lib/auth";
import { requireAdminMutation } from "@/lib/adminRequestGuard";
import { replaceSystemHealthState } from "@/lib/systemHealth";
import { getMasterServerIdentityFromEnv } from "@/lib/serverRegistry";
import { revalidateDashboardCache } from "@/lib/revalidate";

export const dynamic = "force-dynamic";

const parsedMaxBackupImportBytes = Number(process.env.BACKUP_IMPORT_MAX_BYTES);
const MAX_BACKUP_IMPORT_BYTES =
    Number.isFinite(parsedMaxBackupImportBytes) && parsedMaxBackupImportBytes > 0
        ? Math.floor(parsedMaxBackupImportBytes)
        : 50 * 1024 * 1024;

class BackupPayloadTooLargeError extends Error {
    constructor() {
        super("backup_payload_too_large");
        this.name = "BackupPayloadTooLargeError";
    }
}

async function readJsonBodyWithLimit(req: NextRequest): Promise<unknown> {
    const contentLength = Number(req.headers.get("content-length") || "0");
    if (Number.isFinite(contentLength) && contentLength > MAX_BACKUP_IMPORT_BYTES) {
        throw new BackupPayloadTooLargeError();
    }

    if (!req.body) return null;

    const reader = req.body.getReader();
    const decoder = new TextDecoder();
    let bytesRead = 0;
    let raw = "";

    while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        bytesRead += value.byteLength;
        if (bytesRead > MAX_BACKUP_IMPORT_BYTES) {
            throw new BackupPayloadTooLargeError();
        }
        raw += decoder.decode(value, { stream: true });
    }

    raw += decoder.decode();
    if (!raw.trim()) return null;

    return JSON.parse(raw);
}

export async function POST(req: NextRequest) {
    const auth = await requireAdminMutation(req);
    if (isAuthError(auth)) return auth;

    try {
        const body = await readJsonBodyWithLimit(req) as any;

        if (!body || body.version !== "1.0" || !body.data) {
            return NextResponse.json({ error: "Invalid backup file format. Expected version 1.0 JSON generated by JellyTrack." }, { status: 400 });
        }

        const { servers, users, media, playbackHistory, telemetryEvents, settings, systemHealth } = body.data;

        const masterIdentity = getMasterServerIdentityFromEnv();
        const normalizedServers = Array.isArray(servers) && servers.length > 0
            ? servers.map((s: Record<string, unknown>, index: number) => ({
                id: (typeof s.id === "string" && s.id) ? s.id : randomUUID(),
                jellyfinServerId: (typeof s.jellyfinServerId === "string" && s.jellyfinServerId)
                    ? s.jellyfinServerId
                    : `imported-server-${index + 1}`,
                name: (typeof s.name === "string" && s.name) ? s.name : `Imported Server ${index + 1}`,
                url: (typeof s.url === "string" && s.url) ? s.url : masterIdentity.url,
                isActive: typeof s.isActive === "boolean" ? s.isActive : true,
                createdAt: s.createdAt ? new Date(String(s.createdAt)) : new Date(),
                updatedAt: s.updatedAt ? new Date(String(s.updatedAt)) : new Date(),
            }))
            : [{
                id: randomUUID(),
                jellyfinServerId: masterIdentity.jellyfinServerId,
                name: masterIdentity.name,
                url: masterIdentity.url,
                isActive: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            }];

        const defaultServerId = normalizedServers[0].id;

        // Restore BigInt fields that were serialized as strings during export
        if (media && Array.isArray(media)) {
            for (const m of media) {
                if (m.durationMs !== undefined && m.durationMs !== null) {
                    m.durationMs = BigInt(m.durationMs);
                }
            }
        }
        if (playbackHistory && Array.isArray(playbackHistory)) {
            for (const h of playbackHistory) {
                // Convert date strings back to Date objects for Prisma
                if (h.startedAt && typeof h.startedAt === 'string') h.startedAt = new Date(h.startedAt);
                if (h.endedAt && typeof h.endedAt === 'string') h.endedAt = new Date(h.endedAt);
            }
        }
        if (telemetryEvents && Array.isArray(telemetryEvents)) {
            for (const e of telemetryEvents) {
                if (e.positionMs !== undefined && e.positionMs !== null) {
                    e.positionMs = BigInt(e.positionMs);
                }
                if (e.createdAt && typeof e.createdAt === 'string') e.createdAt = new Date(e.createdAt);
            }
        }

        // Perform atomic restore transaction
        await prisma.$transaction(async (tx) => {
            // 1. Clear current database completely (Volatile first, then records)
            await tx.activeStream.deleteMany();
            await tx.playbackHistory.deleteMany();
            await tx.media.deleteMany();
            await tx.user.deleteMany();
            await tx.server.deleteMany();
            await tx.systemHealthEvent.deleteMany();
            await tx.systemHealthState.deleteMany();
            await tx.globalSettings.deleteMany();

            // 2. Insert new records from JSON
            if (normalizedServers.length > 0) {
                await tx.server.createMany({ data: normalizedServers });
            }

            if (users && users.length > 0) {
                const usersToInsert = users.map((u: any) => ({
                    id: u.id,
                    serverId: u.serverId || defaultServerId,
                    jellyfinUserId: u.jellyfinUserId,
                    username: u.username,
                    isActive: typeof u.isActive === "boolean" ? u.isActive : true,
                    lastActive: u.lastActive ? new Date(String(u.lastActive)) : null,
                    createdAt: u.createdAt ? new Date(String(u.createdAt)) : new Date(),
                    updatedAt: u.updatedAt ? new Date(String(u.updatedAt)) : new Date(),
                }));
                await tx.user.createMany({ data: usersToInsert });
            }

            if (media && media.length > 0) {
                const mediaToInsert = media.map((m: any) => ({
                    id: m.id,
                    serverId: m.serverId || defaultServerId,
                    jellyfinMediaId: m.jellyfinMediaId,
                    title: m.title,
                    type: m.type,
                    collectionType: m.collectionType || null,
                    libraryName: m.libraryName || null,
                    genres: Array.isArray(m.genres) ? m.genres : [],
                    resolution: m.resolution || null,
                    durationMs: m.durationMs != null ? BigInt(String(m.durationMs)) : null,
                    size: m.size != null ? BigInt(String(m.size)) : null,
                    directors: Array.isArray(m.directors) ? m.directors : [],
                    actors: Array.isArray(m.actors) ? m.actors : [],
                    studios: Array.isArray(m.studios) ? m.studios : [],
                    parentId: m.parentId || null,
                    artist: m.artist || null,
                    dateAdded: m.dateAdded ? new Date(String(m.dateAdded)) : null,
                    createdAt: m.createdAt ? new Date(String(m.createdAt)) : new Date(),
                    updatedAt: m.updatedAt ? new Date(String(m.updatedAt)) : new Date(),
                }));
                await tx.media.createMany({ data: mediaToInsert });
            }

            const playbackToInsert = Array.isArray(playbackHistory)
                ? playbackHistory.map((ph: any) => ({
                    id: ph.id,
                    serverId: ph.serverId || defaultServerId,
                    userId: ph.userId || null,
                    mediaId: ph.mediaId,
                    playMethod: ph.playMethod,
                    eventSource: ph.eventSource || "playback",
                    sourceEventId: ph.sourceEventId || null,
                    clientName: ph.clientName || null,
                    deviceName: ph.deviceName || null,
                    ipAddress: ph.ipAddress || null,
                    country: ph.country || null,
                    city: ph.city || null,
                    durationWatched: typeof ph.durationWatched === "number" ? ph.durationWatched : 0,
                    startedAt: ph.startedAt ? new Date(String(ph.startedAt)) : new Date(),
                    endedAt: ph.endedAt ? new Date(String(ph.endedAt)) : null,
                    audioLanguage: ph.audioLanguage || null,
                    audioCodec: ph.audioCodec || null,
                    subtitleLanguage: ph.subtitleLanguage || null,
                    subtitleCodec: ph.subtitleCodec || null,
                    bitrate: typeof ph.bitrate === "number" ? ph.bitrate : null,
                    pauseCount: typeof ph.pauseCount === "number" ? ph.pauseCount : 0,
                    audioChanges: typeof ph.audioChanges === "number" ? ph.audioChanges : 0,
                    subtitleChanges: typeof ph.subtitleChanges === "number" ? ph.subtitleChanges : 0,
                    seekCount: typeof ph.seekCount === "number" ? ph.seekCount : 0,
                    rewatchCount: typeof ph.rewatchCount === "number" ? ph.rewatchCount : 0,
                    speedChangeCount: typeof ph.speedChangeCount === "number" ? ph.speedChangeCount : 0,
                    maxPlaybackRate: typeof ph.maxPlaybackRate === "number" ? ph.maxPlaybackRate : null,
                }))
                : [];

            if (playbackToInsert.length > 0) {
                await tx.playbackHistory.createMany({ data: playbackToInsert });
            }

            if (telemetryEvents && telemetryEvents.length > 0) {
                const playbackServerMap = new Map<string, string>();
                for (const ph of playbackToInsert) {
                    if (ph.id) playbackServerMap.set(String(ph.id), String(ph.serverId || defaultServerId));
                }
                const telemetryToInsert = telemetryEvents.map((ev: any) => ({
                    id: ev.id,
                    serverId: ev.serverId || playbackServerMap.get(String(ev.playbackId)) || defaultServerId,
                    playbackId: ev.playbackId,
                    eventType: ev.eventType,
                    positionMs: ev.positionMs != null ? BigInt(String(ev.positionMs)) : BigInt(0),
                    metadata: ev.metadata || null,
                    createdAt: ev.createdAt ? new Date(String(ev.createdAt)) : new Date(),
                }));
                await tx.telemetryEvent.createMany({ data: telemetryToInsert });
            }
            if (settings) {
                // Strip legacy jellyfinUrl/jellyfinApiKey fields (now env vars)
                const cs = settings as Record<string, unknown>;
                await tx.globalSettings.create({
                    data: {
                        id: "global",
                        discordWebhookUrl: (cs['discordWebhookUrl'] as string) ?? null,
                        discordAlertCondition: (cs['discordAlertCondition'] as string) ?? "ALL",
                        discordAlertsEnabled: (cs['discordAlertsEnabled'] as boolean) ?? false,
                        excludedLibraries: (cs['excludedLibraries'] as string[]) ?? [],
                        syncCronHour: (cs['syncCronHour'] as number) ?? 3,
                        syncCronMinute: (cs['syncCronMinute'] as number) ?? 0,
                        backupCronHour: (cs['backupCronHour'] as number) ?? 3,
                        backupCronMinute: (cs['backupCronMinute'] as number) ?? 30,
                        defaultLocale: (cs['defaultLocale'] as string) ?? "en",
                        timeFormat: (cs['timeFormat'] as string) ?? "24h",
                        maxConcurrentTranscodes: (cs['maxConcurrentTranscodes'] as number) ?? 0,
                        wrappedVisible: (cs['wrappedVisible'] as boolean) ?? true,
                        wrappedPeriodEnabled: (cs['wrappedPeriodEnabled'] as boolean) ?? true,
                        wrappedStartMonth: (cs['wrappedStartMonth'] as number) ?? 12,
                        wrappedStartDay: (cs['wrappedStartDay'] as number) ?? 1,
                        wrappedEndMonth: (cs['wrappedEndMonth'] as number) ?? 1,
                        wrappedEndDay: (cs['wrappedEndDay'] as number) ?? 31,
                        pluginKeyRotationDays: (cs['pluginKeyRotationDays'] as number) ?? 90,
                        pluginAutoRotateEnabled: (cs['pluginAutoRotateEnabled'] as boolean) ?? false,
                        pluginKeyRotationGraceHours: (cs['pluginKeyRotationGraceHours'] as number) ?? 24,
                        pluginTelemetrySettings: (cs['pluginTelemetrySettings'] as any) ?? null,
                        authRememberThirtyDaysEnabled: (cs['authRememberThirtyDaysEnabled'] as boolean) ?? true,
                        authSessionsRevokedAt: cs['authSessionsRevokedAt'] ? new Date(String(cs['authSessionsRevokedAt'])) : null,
                        resolutionThresholds: (cs['resolutionThresholds'] as any) ?? null,
                    }
                });
            }
        }, {
            timeout: 60000 // Give it 60 seconds if the DB is massive
        });

        // Skip library rules
        if (systemHealth) {
            await replaceSystemHealthState(systemHealth);
        }

        revalidateDashboardCache();

        return NextResponse.json({ success: true }, { status: 200 });

    } catch (e: unknown) {
        if (e instanceof BackupPayloadTooLargeError) {
            return NextResponse.json({ error: "Backup import payload is too large." }, { status: 413 });
        }
        if (e instanceof SyntaxError) {
            return NextResponse.json({ error: "Invalid backup JSON." }, { status: 400 });
        }
        const msg = e instanceof Error ? e.message : String(e);
        console.error("[BackupImport] Restauration failed:", e);
        return NextResponse.json({ error: msg || "Failed to restore backup" }, { status: 500 });
    }
}
