import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { requireAdmin, isAuthError } from "@/lib/auth";
// No rules
import { replaceSystemHealthState } from "@/lib/systemHealth";

export const dynamic = "force-dynamic";

export async function POST(req: NextRequest) {
    const auth = await requireAdmin();
    if (isAuthError(auth)) return auth;

    try {
        const body = await req.json();

        if (!body || body.version !== "1.0" || !body.data) {
            return NextResponse.json({ error: "Invalid backup file format. Expected version 1.0 JSON generated by JellyTrack." }, { status: 400 });
        }

        const { users, media, playbackHistory, telemetryEvents, settings, systemHealth } = body.data;

        // Restore BigInt fields that were serialized as strings during export
        if (media && Array.isArray(media)) {
            for (const m of media) {
                if (m.durationMs !== undefined && m.durationMs !== null) {
                    m.durationMs = BigInt(m.durationMs);
                }
            }
        }
        if (playbackHistory && Array.isArray(playbackHistory)) {
            for (const h of playbackHistory) {
                // Convert date strings back to Date objects for Prisma
                if (h.startedAt && typeof h.startedAt === 'string') h.startedAt = new Date(h.startedAt);
                if (h.endedAt && typeof h.endedAt === 'string') h.endedAt = new Date(h.endedAt);
            }
        }
        if (telemetryEvents && Array.isArray(telemetryEvents)) {
            for (const e of telemetryEvents) {
                if (e.positionMs !== undefined && e.positionMs !== null) {
                    e.positionMs = BigInt(e.positionMs);
                }
                if (e.createdAt && typeof e.createdAt === 'string') e.createdAt = new Date(e.createdAt);
            }
        }

        // Perform atomic restore transaction
        await prisma.$transaction(async (tx) => {
            // 1. Clear current database completely (Volatile first, then records)
            await tx.activeStream.deleteMany();
            await tx.playbackHistory.deleteMany();
            await tx.media.deleteMany();
            await tx.user.deleteMany();
            await tx.systemHealthEvent.deleteMany();
            await tx.systemHealthState.deleteMany();
            await tx.globalSettings.deleteMany();

            // 2. Insert new records from JSON
            if (users && users.length > 0) {
                await tx.user.createMany({ data: users });
            }
            if (media && media.length > 0) {
                await tx.media.createMany({ data: media });
            }
            if (playbackHistory && playbackHistory.length > 0) {
                await tx.playbackHistory.createMany({ data: playbackHistory });
            }
            if (telemetryEvents && telemetryEvents.length > 0) {
                await tx.telemetryEvent.createMany({ data: telemetryEvents });
            }
            if (settings) {
                // Strip legacy jellyfinUrl/jellyfinApiKey fields (now env vars)
                const cs = settings as Record<string, unknown>;
                await tx.globalSettings.create({
                    data: {
                        id: (cs['id'] as string) || "global",
                        discordWebhookUrl: (cs['discordWebhookUrl'] as string) ?? null,
                        discordAlertCondition: (cs['discordAlertCondition'] as string) ?? "ALL",
                        discordAlertsEnabled: (cs['discordAlertsEnabled'] as boolean) ?? false,
                        excludedLibraries: (cs['excludedLibraries'] as string[]) ?? [],
                        syncCronHour: (cs['syncCronHour'] as number) ?? 3,
                        syncCronMinute: (cs['syncCronMinute'] as number) ?? 0,
                        backupCronHour: (cs['backupCronHour'] as number) ?? 3,
                        backupCronMinute: (cs['backupCronMinute'] as number) ?? 30,
                        defaultLocale: (cs['defaultLocale'] as string) ?? "fr",
                        timeFormat: (cs['timeFormat'] as string) ?? "24h",
                    }
                });
            }
        }, {
            timeout: 60000 // Give it 60 seconds if the DB is massive
        });

        // Skip library rules
        if (systemHealth) {
            await replaceSystemHealthState(systemHealth);
        }

        return NextResponse.json({ success: true }, { status: 200 });

    } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : String(e);
        console.error("[BackupImport] Restauration failed:", e);
        return NextResponse.json({ error: msg || "Failed to restore backup" }, { status: 500 });
    }
}
