const fs = require('fs'),path=require('path');
const reportDirectory=process.env.GO_QA_OUTPUT || path.resolve(__dirname,'../../scratch/navigation-qa');fs.mkdirSync(reportDirectory,{recursive:true});
if(!process.env.GO_QA_PASSWORD)throw Error('GO_QA_PASSWORD is required');
const base=process.env.GO_QA_URL || 'http://localhost:3310';
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext({ baseURL:base, viewport:{width:1440,height:900} });
  const checks=[];
  function check(name,ok) { checks.push({name,ok:!!ok}); if(!ok)throw Error(name); }
  const login=await context.request.post('/api/auth/login',{headers:{Origin:base},data:{username:process.env.GO_QA_USER||'navigationadmin',password:process.env.GO_QA_PASSWORD}});
  check('Real administrator login',login.ok());
  const user=await login.json();
  await context.route('**/api/auth/me',route=>route.fulfill({json:{...user,role:'admin',jellyfinUserId:'jf-0'}}));
  await context.route('**/api/navigation',route=>route.fulfill({json:{multiServer:true,wrappedVisible:true,appVersion:'2.1.1'}}));
  const page=await context.newPage(); const errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  await page.goto('/about',{waitUntil:'networkidle'});
  const links=await page.locator('#historical-nav a').evaluateAll(as=>as.map(a=>a.getAttribute('href')));
  for(const href of links) {
    await page.goto(href,{waitUntil:'networkidle'});
    const active=await page.locator('#historical-nav a.active').evaluateAll(as=>as.map(a=>a.getAttribute('href')));
    check('Active historical link '+href,active.includes(href));
  }
  await page.goto('/admin/health',{waitUntil:'networkidle'});
  await page.locator('[data-health-panel=cleanup]').focus();await page.keyboard.press('ArrowRight');await page.waitForTimeout(500);
  check('Health ArrowRight selects and focuses security',await page.locator('[data-health-panel=security]').evaluate(el=>el.getAttribute('aria-selected')==='true'&&document.activeElement===el));
  await page.keyboard.press('End');await page.waitForTimeout(500);
  check('Health End selects logs',await page.locator('[data-health-panel=logs]').getAttribute('aria-selected')==='true');
  await page.locator('[data-health-panel=cleanup]').click();await page.waitForTimeout(500);
  await page.locator('[data-cleanup-panel=ghosts]').focus();await page.keyboard.press('ArrowRight');
  check('Cleanup ArrowRight selects abandoned',await page.locator('[data-cleanup-panel=abandoned]').getAttribute('aria-selected')==='true');
  await page.keyboard.press('Home');
  check('Cleanup Home selects ghosts',await page.locator('[data-cleanup-panel=ghosts]').getAttribute('aria-selected')==='true');
  await page.goto('/recent',{waitUntil:'networkidle'});
  check('Recent has no library tabs',await page.locator('.historical-settings-tabs').count()===0);
  await page.goto('/media/artist/Artiste%20Audit',{waitUntil:'networkidle'});
  check('Artist keeps library tabs',await page.locator('.historical-settings-tabs a').count()===4);
  check('Artist no selected library tab',await page.locator('.historical-settings-tabs a.active').count()===0);
  await page.goto('/media/audit-primary-m0',{waitUntil:'networkidle'});
  check('Media detail keeps library tabs',await page.locator('.historical-settings-tabs a').count()===4);
  await page.goto('/logs?tab=system',{waitUntil:'networkidle'});
  await page.locator('#language-trigger').click();await page.locator('[data-locale=en]').click();await page.waitForTimeout(400);
  check('Language retains system query',new URL(page.url()).search==='?tab=system');
  check('Language retains selected system tab',await page.locator('#history-tab-system').getAttribute('aria-selected')==='true');
  await page.goto('/about',{waitUntil:'networkidle'});await page.locator('#sidebar-collapse-btn').click();await page.waitForTimeout(400);
  check('Expanded chevron on reduced sidebar',await page.locator('#sidebar-collapse-btn svg').evaluate(el=>getComputedStyle(el).transform)!=='none');
  await page.locator('#sidebar-search-trigger').click();
  check('Compact search popup visible',await page.locator('#nav-search-input').isVisible());
  await page.locator('#nav-search-input').fill('Movie');await page.waitForTimeout(650);
  check('Compact search results visible',await page.locator('#nav-search-results').isVisible());
  await page.keyboard.press('Escape');await page.locator('#language-trigger').click();
  check('Compact language menu visible',await page.locator('#language-menu').isVisible());await page.keyboard.press('Escape');
  await page.locator('#historical-nav a[href="/media"]').hover();
  check('Compact custom tooltip visible',await page.locator('#navigation-tooltip').isVisible());
  await context.route('**/api/search?q=*',async route=>{await new Promise(resolve=>setTimeout(resolve,400));await route.fulfill({json:{media:[{id:'audit-primary-m0',title:'Delayed result',type:'Movie'}],users:[]}});});
  await page.locator('#sidebar-search-trigger').click();await page.locator('#nav-search-input').fill('delay');await page.waitForTimeout(340);await page.locator('#nav-search-input').fill('');await page.waitForTimeout(550);
  check('Delayed search cannot reopen cleared results',!(await page.locator('#nav-search-results').isVisible()));
  await page.goto('/wrapped/jf-0',{waitUntil:'networkidle'});
  check('Wrapped hides sidebar',!(await page.locator('#app-sidebar').isVisible()));
  check('Wrapped close visible',await page.locator('#wrapped-close-btn').isVisible());
  await page.locator('#wrapped-close-btn').click();await page.waitForTimeout(400);
  check('Wrapped close returns to prior page',new URL(page.url()).pathname==='/about');
  await page.locator('.main-wrapper').evaluate(el=>el.scrollTo(0,400));await page.waitForTimeout(150);
  check('Content can scroll independently',await page.locator('.main-wrapper').evaluate(el=>el.scrollTop)>0);
  await page.locator('#historical-nav a[href="/settings"]').click();await page.waitForTimeout(500);
  check('SPA route restores content scroll position',await page.locator('.main-wrapper').evaluate(el=>el.scrollTop)===0);
  await page.setViewportSize({width:390,height:844});await page.goto('/media',{waitUntil:'networkidle'});
  await page.locator('#mobile-menu-btn').click();await page.locator('#historical-nav a[href="/media"]').click();
  check('Same pathname keeps mobile drawer open',await page.locator('#app-sidebar').evaluate(el=>el.classList.contains('mobile-open')));
  await page.locator('#language-trigger').click();await page.locator('[data-locale=fr]').click();await page.waitForTimeout(500);
  check('Language refresh keeps mobile drawer open',await page.locator('#app-sidebar').evaluate(el=>el.classList.contains('mobile-open')));
  await page.locator('#historical-nav a[href="/recent"]').click();await page.waitForTimeout(500);
  check('Different pathname closes mobile drawer',!(await page.locator('#app-sidebar').evaluate(el=>el.classList.contains('mobile-open'))));
  check('No uncaught JavaScript errors',errors.length===0);
  await browser.close();fs.writeFileSync(path.join(reportDirectory,'focused-results.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks:checks.length,failed:checks.filter(x=>!x.ok),errors}));
})().catch(error=>{console.error(error);process.exit(1);});
