const fs=require('fs'),path=require('path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'docs/users-captures');fs.mkdirSync(out,{recursive:true});
const report={fixture:'Isolated users.db9 users280 histories, no real Jellyfin server; real admin password login; signed real Go AuthSession for standard users.',cases:[],checks:[]};
function check(name,ok,detail){report.checks.push({name,ok:!!ok,detail});console.log((ok?'PASS ':'FAIL ')+name);save();}
function save(){fs.writeFileSync(path.join(root,'docs/users-validation/'+(process.argv.includes('reference')?'main':process.argv.includes('mobile-only')?'go-mobile-last':'go')+'-browser-results.json'),JSON.stringify(report,null,2));}
const go=process.env.GO_QA_URL || 'http://localhost:3330',ref=process.env.REFERENCE_URL || 'http://localhost:3331';
async function capture(context,label,url,expected){const page=await context.newPage(),item={label,url,errors:[],httpErrors:[]};page.on('pageerror',e=>item.errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&!r.url().includes('user-image')&&!r.url().includes('media-image')&&!r.url().includes('poster'))item.httpErrors.push({url:r.url(),status:r.status()});});report.cases.push(item);save();try{await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForSelector(expected,{timeout:60000});await page.waitForTimeout(1400);if(url.includes('/users/')){await page.getByText('Historique de lecture',{exact:true}).first().waitFor({timeout:60000});if(label.startsWith('main')){try{await page.locator('.recharts-wrapper').first().waitFor({timeout:30000});await page.waitForTimeout(1000);}catch(e){item.chartWarning=e.message;}}}item.finalUrl=page.url();item.text=(await page.locator('main').innerText()).slice(0,14000);item.geometry=await page.locator('main').evaluate(el=>({x:el.getBoundingClientRect().x,width:el.getBoundingClientRect().width,scrollWidth:el.scrollWidth,viewport:innerWidth}));await page.screenshot({path:path.join(out,label+'.png'),fullPage:true,timeout:30000});item.screenshot=label+'.png';if(url.includes('/users/')){for(const [title,suffix]of [['Activité sur 30 jours','activity'],['Activité par Jour','charts'],['Historique de lecture','history']]){const heading=page.getByText(title,{exact:true}).first();if(await heading.count()){await heading.scrollIntoViewIfNeeded();await page.waitForTimeout(300);await page.screenshot({path:path.join(out,label+'-'+suffix+'.png'),timeout:30000});}}}check(label+' JS',item.errors.length===0,item.errors);}catch(e){item.error=e.message;console.log('ERROR '+label+' '+e.message);}save();return page;}
(async()=>{const browser=await chromium.launch({headless:true});
if(process.argv.includes('reference')){
 const {encode}=require(path.join(process.env.REFERENCE_ROOT || path.join(root,'scratch/navigation-qa/main-reference'),'node_modules/next-auth/jwt'));
 for(const [label,route,width,theme]of [['main-users-desktop-dark','/users',1440,'dark'],['main-profile-desktop-dark','/users/qa-many',1440,'dark'],['main-users-mobile-dark','/users',390,'dark'],['main-profile-mobile-dark','/users/qa-many',390,'dark'],['main-users-desktop-light','/users',1440,'light'],['main-profile-empty-dark','/users/qa-empty',1440,'dark'],['main-profile-desktop-light','/users/qa-many',1440,'light'],['main-profile-mobile-light','/users/qa-many',390,'light']]){
  const context=await browser.newContext({viewport:{width,height:900},locale:'fr-FR',colorScheme:theme});const now=Math.floor(Date.now()/1000);const token=await encode({secret:process.env.REFERENCE_SECRET || 'navigation-qa-reference-secret-at-least-32-characters',token:{name:'Admin QA',sub:'qa-local',isAdmin:true,jellyfinUserId:'local-admin',authServerName:'QA principal',authServerIsPrimary:true,sessionExpiresAt:now+86400,sessionIssuedAt:now,sessionExpired:false},maxAge:86400});await context.addCookies([{name:'next-auth.session-token',value:token,url:ref},{name:'locale',value:'fr',url:ref}]);await context.addInitScript(t=>localStorage.setItem('theme',t),theme);await capture(context,label,ref+route,route==='/users'?'table':'main h2');await context.close();
 }
}else{
 const auth=await browser.newContext({baseURL:go});const login=await auth.request.post('/api/auth/login',{headers:{Origin:go},data:{username:process.env.GO_QA_USER || 'usersadmin',password:process.env.GO_QA_PASSWORD || 'Users-QA-test-2026!'}});if(!login.ok())throw Error('admin login '+login.status());const state=await auth.storageState();const cookies=JSON.parse(fs.readFileSync(path.join(root,'scratch/users-qa/standard-cookies.json'),'utf8'));
 for(const [label,route,width,theme,uid]of [['go-users-desktop-dark','/users',1440,'dark',null],['go-profile-desktop-dark','/users/qa-many',1440,'dark',null],['go-users-mobile-dark','/users',390,'dark',null],['go-profile-mobile-dark','/users/qa-many',390,'dark',null],['go-users-desktop-light','/users',1440,'light',null],['go-profile-desktop-light','/users/qa-many',1440,'light',null],['go-profile-empty-dark','/users/qa-empty',1440,'dark',null],['go-profile-partial-dark','/users/qa-partial',1440,'dark',null],['go-standard-own-profile','/users/qa-many',1440,'dark','qa-many']]){
  if(process.argv.includes('list-only')&&route!=='/users')continue;
  if(process.argv.includes('mobile-only')&&width>400)continue;
  const context=await browser.newContext({baseURL:go,storageState:uid?undefined:state,viewport:{width,height:900},locale:'fr-FR',colorScheme:theme});if(uid)await context.addCookies([{name:'jellytrack_session',value:cookies[uid],url:go}]);await context.addInitScript(t=>{localStorage.setItem('jt_theme',t);localStorage.setItem('jt_locale','fr');},theme);
  const page=await capture(context,label,go+route,route==='/users'?'#users-body[aria-busy="false"]':'.jt-profile');
  if(label==='go-users-desktop-dark'&&!report.cases.at(-1).error){
   check('users count9',await page.locator('#users-body tr').count()===9);
   await page.locator('#users-search').fill('Many Sessions');check('username search',await page.locator('#users-body tr').count()===1&&await page.locator('#users-body').innerText().then(t=>t.includes('Many Sessions')));
   await page.locator('#users-search').fill('Android TV');check('favorite-client search',await page.locator('#users-body').innerText().then(t=>t.includes('Bob Audit')&&!t.includes('Alice Audit')));
   await page.locator('#users-search').fill('');for(const f of ['inactive30','inactive90','transcoders','never','all']){await page.locator(`[data-filter="${f}"]`).click();check('filter '+f,await page.locator(`[data-filter="${f}"]`).getAttribute('aria-pressed')==='true',{rows:await page.locator('#users-body').innerText()});}
   await page.locator('#users-search').fill('no-matching-account');check('empty search state',await page.locator('#users-body').innerText().then(t=>t.includes('Aucun utilisateur')));await page.locator('#users-search').fill('');
   const downloadP=page.waitForEvent('download');await page.locator('#users-export-json').click();const download=await downloadP;await download.saveAs(path.join(root,'scratch/users-qa/users-export.json'));const exported=JSON.parse(fs.readFileSync(path.join(root,'scratch/users-qa/users-export.json'),'utf8'));check('JSON export9 real users',exported.length===9);
   const link=page.locator('a[href="/users/qa-many"]').first();await link.click();await page.waitForTimeout(1200);check('profile link navigates',new URL(page.url()).pathname==='/users/qa-many');
  }
  if(uid){const own=await context.request.get('/api/users/qa-many'),other=await context.request.get('/api/users/qa-empty'),list=await context.request.get('/api/users');check('standard own API',own.status()===200);check('standard other profile denied',other.status()===403);check('standard list denied',list.status()===403);}
  await context.close();
 }
 await auth.close();
}
await browser.close();save();if(report.cases.some(c=>c.error||c.errors.length)||report.checks.some(c=>!c.ok))process.exitCode=1;console.log('Completed '+report.cases.length+' captures; '+report.checks.length+' checks.');})().catch(e=>{report.fatal=e.stack;save();console.error(e);process.exit(1)});
